// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC16EhkuF1O7t6kYO4tupecU6bosYyi_sg',
    appId: '1:792071942879:web:eedcf2a1067f9e0af7af6a',
    messagingSenderId: '792071942879',
    projectId: 'toko-app-28a5b',
    authDomain: 'toko-app-28a5b.firebaseapp.com',
    storageBucket: 'toko-app-28a5b.firebasestorage.app',
    measurementId: 'G-GZPG333VFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWyTIF9DHHss83InAV0dW03cPovGHHDuo',
    appId: '1:792071942879:android:ee5cccaf652624adf7af6a',
    messagingSenderId: '792071942879',
    projectId: 'toko-app-28a5b',
    storageBucket: 'toko-app-28a5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU6rIdXraN2gD8rnicSwOJp6IDLBySpj8',
    appId: '1:792071942879:ios:6ffb53f2eb979dcbf7af6a',
    messagingSenderId: '792071942879',
    projectId: 'toko-app-28a5b',
    storageBucket: 'toko-app-28a5b.firebasestorage.app',
    iosBundleId: 'com.toko.app.tokoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU6rIdXraN2gD8rnicSwOJp6IDLBySpj8',
    appId: '1:792071942879:ios:6ffb53f2eb979dcbf7af6a',
    messagingSenderId: '792071942879',
    projectId: 'toko-app-28a5b',
    storageBucket: 'toko-app-28a5b.firebasestorage.app',
    iosBundleId: 'com.toko.app.tokoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC16EhkuF1O7t6kYO4tupecU6bosYyi_sg',
    appId: '1:792071942879:web:700f5153a4f786bdf7af6a',
    messagingSenderId: '792071942879',
    projectId: 'toko-app-28a5b',
    authDomain: 'toko-app-28a5b.firebaseapp.com',
    storageBucket: 'toko-app-28a5b.firebasestorage.app',
    measurementId: 'G-RLP7FJG4C3',
  );
}
